verify tag and version match

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -28,11 +28,17 @@ jobs:
           echo "SHORT_GIT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
           echo "QUILIBRIUM_VERSION=$(cat ${GITHUB_WORKSPACE}/node/config/version.go | grep -A 1 'func GetVersion() \[\]byte {' | grep -Eo '0x[0-9a-fA-F]+' | xargs printf '%d.%d.%d')" >> $GITHUB_ENV
       -
-        name: log tag and version
+        name: verify tag and version match
         run: |
-          echo "git tag: ${GIT_TAG}"
-          echo "short git sha: ${SHORT_GIT_SHA}"
-          echo "quilibrim version: ${QUILIBRIUM_VERSION}"
+          if [ "${GIT_TAG}" = "v${QUILIBRIUM_VERSION}-${SHORT_GIT_SHA}" ]; then
+            echo "git tag: ${GIT_TAG}"
+            echo "short git sha: ${SHORT_GIT_SHA}"
+            echo "quilibrim version: ${QUILIBRIUM_VERSION}"
+          else
+            echo "version in node/config/version.go (${QUILIBRIUM_VERSION}) does not match tag (${GIT_TAG})"
+            echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
+            exit 1
+          fi
       -
         name: go setup
         uses: actions/setup-go@v5
@@ -107,5 +113,9 @@ jobs:
       - name: publish
         uses: softprops/action-gh-release@v2
         with:
-          files: ${GITHUB_WORKSPACE}/quilibrium-*
+          files: |
+            ${GITHUB_WORKSPACE}/quilibrium-${GIT_TAG}-darwin-arm64
+            ${GITHUB_WORKSPACE}/quilibrium-${GIT_TAG}-darwin-arm64.dgst
+            ${GITHUB_WORKSPACE}/quilibrium-${GIT_TAG}-linux-amd64
+            ${GITHUB_WORKSPACE}/quilibrium-${GIT_TAG}-linux-amd64.dgst
           prerelease: true
